sylius_grid:
  grids:
    ecolos_sylius_nutrinfo_plugin_admin_nutrinfo_active:
      driver:
        name: doctrine/orm
        options:
          class: Ecolos\SyliusNutrinfoPlugin\Entity\NutrinfoActive
      fields:
        id:
          type: string
          label: "ID"
        name:
          type: string
          label: "sylius.ui.name"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
