services:
  ecolos_sylius_nutritional_information_plugin.form.type.nutritional_information:
    class: Ecolos\SyliusNutritionalInformation\Form\Type\NutritionalInformationType
    tags:
      - { name: form.type}

  ecolos_sylius_nutritional_information_plugin.form.extension.type.product_variant:
    class: Ecolos\SyliusNutritionalInformationPlugin\Extension\ProductVariantTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType }
